export const CREATE_DICTIONARY = 'CREATE_DICTIONARY'
export const CREATE_DICTIONARY_SUCCESS = 'CREATE_DICTIONARY_SUCCESS'
export const CREATE_DICTIONARY_FAILURE = 'CREATE_DICTIONARY_FAILURE'

export const GET_DICTIONARIES = 'GET_DICTIONARIES'
export const GET_DICTIONARIES_SUCCESS = 'GET_DICTIONARIES_SUCCESS'
export const GET_DICTIONARIES_FAILURE = 'GET_DICTIONARIES_FAILURE'

export const DELETE_DICTIONARY = 'DELETE_DICTIONARY'
export const DELETE_DICTIONARY_SUCCESS = 'DELETE_DICTIONARY_SUCCESS'
export const DELETE_DICTIONARY_FAILURE = 'DELETE_DICTIONARY_FAILURE'

export const UPDATE_DICTIONARY = 'UPDATE_DICTIONARY'
export const UPDATE_DICTIONARY_SUCCESS = 'UPDATE_DICTIONARY_SUCCESS'
export const UPDATE_DICTIONARY_FAILURE = 'UPDATE_DICTIONARY_FAILURE'